name: Tox
on: [push, pull_request]

jobs:
  sphinx_build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run Tox
        uses: ./.github/actions/sphinx-build-all
      - name: Archive HTML documents
        uses: actions/upload-artifact@v5
        with:
          name: pygobject-tutorial
          path: build/html
